sudo: false
language: python
# cache package wheels (1 cache per python version)
cache: pip
python: 3.5

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - tox
  - codecov
  - ci/lint.sh
  - ci/mypy.sh
