sudo: false
language: python
# cache package wheels (1 cache per python version)
cache: pip

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install tox

matrix:
  include:
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.7
      dist: xenial
      sudo: required
      env:
        - TOX_ENV=py37

script:
  - tox -e $TOX_ENV
  - codecov
  - ci/lint.sh
  - ci/mypy.sh