sudo: false
language: python
# cache package wheels (1 cache per python version)
cache: pip
`python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install tox

script:
  - tox
  - codecov
  - ci/lint.sh
  - ci/mypy.sh